# Név
name: Első Pipeine

# Mikor induljon el
on:
  pull_request

# Fázisok
jobs:
  elso:
    name: Első fázis
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltés
        uses: actions/checkout@v4

      - name: Python 3.x
        uses: actions/setup-python@v5
        with:
          python.version: "3.12"
      
      - name: Python verzió ellenőrzés
        run: python --version
      
      - name: Kód futtatás
        run: python main.py
        working-directory: .app
