# Név
name: Első Pipeine

# Mikor induljon
on:
  pull_request

# Fázisok
jobs:
  elso:
    name: első fázis
    runs-on: ubuntu-latest

    steps:
      - name: Egy soros parancs
        run: echo "Sziasztok! Én egy feladat vagyok egy pipeline-on belül"
